version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Adjust to the version of Node.js you are using
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running linting...
      - npm run lint
      - echo Running TypeScript compilation...
      - npm run test:typescript

  build:
    commands:
      - echo Running all tests...
      - npm test

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Opening coverage report...
      - npm run coverage

artifacts:
  files:
    - '**/*'
  base-directory: 'build'  # Adjust if your build outputs are in a different directory
  discard-paths: yes  # Set to yes to avoid including unnecessary directory structure in S3

cache:
  paths:
    - 'node_modules/**/*'
