version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running linting...
      - npm run lint
      - echo Running TypeScript compilation...
      - npm run test:typescript

  build:
    commands:
      - echo Running all tests...
      - npm test

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Coverage report generated

artifacts:
  files:
    - '**/*'
  base-directory: '.'  # Adjust this to the correct path if necessary

cache:
  paths:
    - 'node_modules/**/*'

